List<String> locations = [
    "Jurong East",
    "Bukit Batok",
    "Bukit Gombak",
    "Choa Chu Kang",
    "Yew Tee",
    "Kranji",
    "Marsiling",
    "Woodlands",
    "Admiralty",
    "Sembawang",
    "Yishun",
    "Khatib",
    "Yio Chu Kang",
    "Ang Mo Kio",
    "Bishan",
    "Braddell",
    "Toa Payoh",
    "Novena",
    "Newton",
    "Orchard",
    "Somerset",
    "Dhoby Ghaut",
    "City Hall",
    "Raffles Place",
    "Marina Bay",
    "Marina South Pier",
    "Tuas Link",
    "Tuas West Road",
    "Tuas Crescent",
    "Gul Circle",
    "Joo Koon",
    "Pioneer",
    "Boon Lay",
    "Lakeside",
    "Chinese Garden",
    "Clementi",
    "Dover",
    "Buona Vista",
    "Commonwealth",
    "Queenstown",
    "Redhill",
    "Tiong Bahru",
    "Outram Park",
    "Tanjong Pagar",
    "Bugis",
    "Lavender",
    "Kallang",
    "Aljunied",
    "Paya Lebar",
    "Eunos",
    "Kembangan",
    "Bedok",
    "Tanah Merah",
    "Simei",
    "Tampines",
    "Pasir Ris",
    "Expo",
    "Changi Airport",
    "HarbourFront",
    "Chinatown",
    "Clarke Quay",
    "Little India",
    "Farrer Park",
    "Boon Keng",
    "Potong Pasir",
    "Woodleigh",
    "Serangoon",
    "Kovan",
    "Hougang",
    "Buangkok",
    "Sengkang",
    "Punggol",
    "Bras Basah",
    "Esplanade",
    "Promenade",
    "Nicoll Highway",
    "Stadium",
    "Mountbatten",
    "Dakota",
    "MacPherson",
    "Tai Seng",
    "Bartley",
    "Lorong Chuan",
    "Marymount",
    "Caldecott",
    "Botanic Gardens",
    "Farrer Road",
    "Holland Village",
    "one-north",
    "Kent Ridge",
    "Haw Par Villa",
    "Pasir Panjang",
    "Labrador Park",
    "Telok Blangah",
    "Bayfront",
    "Bukit Panjang",
    "Cashew",
    "Hillview",
    "Beauty World",
    "King Albert Park",
    "Sixth Avenue",
    "Tan Kah Kee",
    "Stevens",
    "Rochor",
    "Downtown",
    "Telok Ayer",
    "Fort Canning",
    "Bencoolen",
    "Jalan Besar",
    "Bendemeer",
    "Geylang Bahru",
    "Mattar",
    "Ubi",
    "Kaki Bukit",
    "Bedok North",
    "Bedok Reservoir",
    "Tampines West",
    "Tampines East",
    "Upper Changi",
  ];
  

  // TO INCLUDE LIST OF ALL LOCATIONS TO BE QUERIED